name: Build
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: create-pin-refs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#create-pin-refs
      - run: nix build .#test
