name: Build
on:
  push:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: create-pin-refs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix build .#create-pin-refs
      - run: |
          nix build .#test
      - run: |
          nix build .#test-linux
          cachix pin create-pin-refs test-linux ./result
