name: Build
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        build:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: create-pin-refs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          packages=(
            default
            create-pin-refs
            test
            # test-linux
          )
          for pkg in "${packages[@]}";do
            nix build .#"$pkg"
            cachix push create-pin-refs ./result
            cachix pin create-pin-refs "$pkg".${{ matrix.build.system }} ./result --keep-revisions 1
          done
